"""OS presets for ohbs_cli.py.

Maps each supported --os value to its engine/catalog/guidance/sections/template
file paths (relative to the repo root) and display name.
"""

OS_PRESETS = {
    "tencentos3": {
        "engine": "ohbs-tencentos3-ansible/roles/ohbs-tencentos3/files/ohbs_engine.py",
        "catalog": "ohbs-tencentos3-ansible/roles/ohbs-tencentos3/files/rules.json",
        "guidance": "ohbs-tencentos3-ansible/roles/ohbs-tencentos3/files/guidance.json",
        "sections": "ohbs-tencentos3-ansible/roles/ohbs-tencentos3/files/sections.json",
        "template": "ohbs-tencentos3-ansible/roles/ohbs-tencentos3/templates/report.html.j2",
        "name": "CIS TencentOS Server 3 Benchmark",
    },
    "tencentos4": {
        "engine": "ohbs-tencentos4-ansible/roles/ohbs-tencentos4/files/ohbs_engine.py",
        "catalog": "ohbs-tencentos4-ansible/roles/ohbs-tencentos4/files/rules.json",
        "guidance": "ohbs-tencentos4-ansible/roles/ohbs-tencentos4/files/guidance.json",
        "sections": "ohbs-tencentos4-ansible/roles/ohbs-tencentos4/files/sections.json",
        "template": "ohbs-tencentos4-ansible/roles/ohbs-tencentos4/templates/report.html.j2",
        "name": "CIS TencentOS Server 4 Benchmark",
    },
    "win2016": {
        "engine": "ohbs-win2016-ansible/roles/ohbs-win2016/files/ohbs_engine.ps1",
        "catalog": "ohbs-win2016-ansible/roles/ohbs-win2016/files/rules.json",
        "guidance": "ohbs-win2016-ansible/roles/ohbs-win2016/files/guidance.json",
        "sections": "ohbs-win2016-ansible/roles/ohbs-win2016/files/sections.json",
        "template": "ohbs-win2016-ansible/roles/ohbs-win2016/templates/report.html.j2",
        "name": "CIS Microsoft Windows Server 2016 Benchmark",
    },
    "win2019": {
        "engine": "ohbs-win2019-ansible/roles/ohbs-win2019/files/ohbs_engine.ps1",
        "catalog": "ohbs-win2019-ansible/roles/ohbs-win2019/files/rules.json",
        "guidance": "ohbs-win2019-ansible/roles/ohbs-win2019/files/guidance.json",
        "sections": "ohbs-win2019-ansible/roles/ohbs-win2019/files/sections.json",
        "template": "ohbs-win2019-ansible/roles/ohbs-win2019/templates/report.html.j2",
        "name": "CIS Microsoft Windows Server 2019 Benchmark",
    },
    "win2022": {
        "engine": "ohbs-win2022-ansible/roles/ohbs-win2022/files/ohbs_engine.ps1",
        "catalog": "ohbs-win2022-ansible/roles/ohbs-win2022/files/rules.json",
        "guidance": "ohbs-win2022-ansible/roles/ohbs-win2022/files/guidance.json",
        "sections": "ohbs-win2022-ansible/roles/ohbs-win2022/files/sections.json",
        "template": "ohbs-win2022-ansible/roles/ohbs-win2022/templates/report.html.j2",
        "name": "CIS Microsoft Windows Server 2022 Benchmark",
    },
    "win2025": {
        "engine": "ohbs-win2025-ansible/roles/ohbs-win2025/files/ohbs_engine.ps1",
        "catalog": "ohbs-win2025-ansible/roles/ohbs-win2025/files/rules.json",
        "guidance": "ohbs-win2025-ansible/roles/ohbs-win2025/files/guidance.json",
        "sections": "ohbs-win2025-ansible/roles/ohbs-win2025/files/sections.json",
        "template": "ohbs-win2025-ansible/roles/ohbs-win2025/templates/report.html.j2",
        "name": "CIS Microsoft Windows Server 2025 Benchmark",
    },
    "rhel8": {
        "engine": "ohbs-rhel8-ansible/roles/ohbs-rhel8/files/ohbs_engine.py",
        "catalog": "ohbs-rhel8-ansible/roles/ohbs-rhel8/files/rules.json",
        "guidance": "ohbs-rhel8-ansible/roles/ohbs-rhel8/files/guidance.json",
        "sections": "ohbs-rhel8-ansible/roles/ohbs-rhel8/files/sections.json",
        "template": "ohbs-rhel8-ansible/roles/ohbs-rhel8/templates/report.html.j2",
        "name": "CIS Red Hat Enterprise Linux 8 Benchmark",
    },
    "rhel9": {
        "engine": "ohbs-rhel9-ansible/roles/ohbs-rhel9/files/ohbs_engine.py",
        "catalog": "ohbs-rhel9-ansible/roles/ohbs-rhel9/files/rules.json",
        "guidance": "ohbs-rhel9-ansible/roles/ohbs-rhel9/files/guidance.json",
        "sections": "ohbs-rhel9-ansible/roles/ohbs-rhel9/files/sections.json",
        "template": "ohbs-rhel9-ansible/roles/ohbs-rhel9/templates/report.html.j2",
        "name": "CIS Red Hat Enterprise Linux 9 Benchmark",
    },
    "rhel10": {
        "engine": "ohbs-rhel10-ansible/roles/ohbs-rhel10/files/ohbs_engine.py",
        "catalog": "ohbs-rhel10-ansible/roles/ohbs-rhel10/files/rules.json",
        "guidance": "ohbs-rhel10-ansible/roles/ohbs-rhel10/files/guidance.json",
        "sections": "ohbs-rhel10-ansible/roles/ohbs-rhel10/files/sections.json",
        "template": "ohbs-rhel10-ansible/roles/ohbs-rhel10/templates/report.html.j2",
        "name": "CIS Red Hat Enterprise Linux 10 Benchmark",
    },
    "sles15": {
        "engine": "ohbs-sles15-ansible/roles/ohbs-sles15/files/ohbs_engine.py",
        "catalog": "ohbs-sles15-ansible/roles/ohbs-sles15/files/rules.json",
        "guidance": "ohbs-sles15-ansible/roles/ohbs-sles15/files/guidance.json",
        "sections": "ohbs-sles15-ansible/roles/ohbs-sles15/files/sections.json",
        "template": "ohbs-sles15-ansible/roles/ohbs-sles15/templates/report.html.j2",
        "name": "CIS SUSE Linux Enterprise 15 Benchmark",
    },
    "sles16": {
        "engine": "ohbs-sles16-ansible/roles/ohbs-sles16/files/ohbs_engine.py",
        "catalog": "ohbs-sles16-ansible/roles/ohbs-sles16/files/rules.json",
        "guidance": "ohbs-sles16-ansible/roles/ohbs-sles16/files/guidance.json",
        "sections": "ohbs-sles16-ansible/roles/ohbs-sles16/files/sections.json",
        "template": "ohbs-sles16-ansible/roles/ohbs-sles16/templates/report.html.j2",
        "name": "CIS SUSE Linux Enterprise 16 Benchmark",
    },
    "ubuntu2004": {
        "engine": "ohbs-ubuntu2004-ansible/roles/ohbs-ubuntu2004/files/ohbs_engine.py",
        "catalog": "ohbs-ubuntu2004-ansible/roles/ohbs-ubuntu2004/files/rules.json",
        "guidance": "ohbs-ubuntu2004-ansible/roles/ohbs-ubuntu2004/files/guidance.json",
        "sections": "ohbs-ubuntu2004-ansible/roles/ohbs-ubuntu2004/files/sections.json",
        "template": "ohbs-ubuntu2004-ansible/roles/ohbs-ubuntu2004/templates/report.html.j2",
        "name": "CIS Ubuntu Linux 20.04 LTS Benchmark",
    },
    "ubuntu2204": {
        "engine": "ohbs-ubuntu2204-ansible/roles/ohbs-ubuntu2204/files/ohbs_engine.py",
        "catalog": "ohbs-ubuntu2204-ansible/roles/ohbs-ubuntu2204/files/rules.json",
        "guidance": "ohbs-ubuntu2204-ansible/roles/ohbs-ubuntu2204/files/guidance.json",
        "sections": "ohbs-ubuntu2204-ansible/roles/ohbs-ubuntu2204/files/sections.json",
        "template": "ohbs-ubuntu2204-ansible/roles/ohbs-ubuntu2204/templates/report.html.j2",
        "name": "CIS Ubuntu Linux 22.04 LTS Benchmark",
    },
    "ubuntu2404": {
        "engine": "ohbs-ubuntu2404-ansible/roles/ohbs-ubuntu2404/files/ohbs_engine.py",
        "catalog": "ohbs-ubuntu2404-ansible/roles/ohbs-ubuntu2404/files/rules.json",
        "guidance": "ohbs-ubuntu2404-ansible/roles/ohbs-ubuntu2404/files/guidance.json",
        "sections": "ohbs-ubuntu2404-ansible/roles/ohbs-ubuntu2404/files/sections.json",
        "template": "ohbs-ubuntu2404-ansible/roles/ohbs-ubuntu2404/templates/report.html.j2",
        "name": "CIS Ubuntu Linux 24.04 LTS Benchmark",
    },
}
