#!/usr/bin/env python3
"""Convert a CIS engine result.json to a simplified XCCDF 1.2 Benchmark XML.

Usage:
    python3 scripts/export_xccdf.py <result.json> [output.xml]
"""

import json
import os
import sys
from datetime import datetime, timezone
from xml.etree import ElementTree as ET


XCCDF_NS = "http://checklists.nist.gov/xccdf/1.2"


def _q(tag):
    return "{%s}%s" % (XCCDF_NS, tag)


def _status_to_xccdf(status):
    return {
        "pass": "pass",
        "fail": "fail",
        "error": "error",
        "manual": "notchecked",
        "notapplicable": "notapplicable",
        "skipped": "notchecked",
        "waived": "notchecked",
    }.get(status, "notchecked")


def _parse_timestamp(value):
    if not value:
        return datetime.now(timezone.utc)
    try:
        return datetime.strptime(value, "%Y-%m-%dT%H:%M:%S%z")
    except ValueError:
        return datetime.now(timezone.utc)


def to_xccdf(data):
    benchmark_id = data.get("benchmark", "cis-os-benchmark")
    started = data.get("started_at") or datetime.now(timezone.utc).isoformat()
    started_dt = _parse_timestamp(started)

    root = ET.Element(
        _q("Benchmark"),
        id="xccdf_cis-os_benchmark_%s" % benchmark_id,
        style="SCAP_1.3",
        resolved="1",
    )
    root.set("xmlns", XCCDF_NS)

    ET.SubElement(root, _q("status"), date=started_dt.strftime("%Y-%m-%d")).text = "accepted"
    ET.SubElement(root, _q("title")).text = data.get("benchmark", "CIS Benchmark")
    ET.SubElement(root, _q("version"), update=str(data.get("schema", 1))).text = data.get(
        "engine_version", "1.0.0"
    )
    ET.SubElement(root, _q("description")).text = "Generated by cis-os %s mode" % data.get(
        "mode", "scan"
    )

    for rule in data.get("results", []):
        rule_el = ET.SubElement(root, _q("Rule"), id=rule["id"])
        ET.SubElement(rule_el, _q("title")).text = rule.get("title", "")
        ident = ET.SubElement(rule_el, _q("ident"), system="http://cce.mitre.org")
        ident.text = rule.get("cce") or rule["id"]

    host = data.get("host", {})
    hostname = host.get("hostname") or "unknown"

    test_result = ET.SubElement(
        root, _q("TestResult"), id="xccdf_cis-os_testresult_%s" % benchmark_id
    )
    ET.SubElement(test_result, _q("title")).text = "%s scan result" % data.get(
        "benchmark", "CIS Benchmark"
    )
    ET.SubElement(test_result, _q("target")).text = hostname
    identity = ET.SubElement(
        test_result, _q("identity"), authenticated="1", privileged="1"
    )
    identity.text = os.environ.get("USER", "unknown")

    summary = data.get("summary", {}).get("all", {})
    score = data.get("score")
    if score is None:
        score = summary.get("score", 0.0)
    score_el = ET.SubElement(
        test_result, _q("score"), system="urn:xccdf:scoring:default", maximum="100"
    )
    score_el.text = str(score)

    for rule in data.get("results", []):
        rr = ET.SubElement(
            test_result,
            _q("rule-result"),
            idref=rule["id"],
            time=started_dt.isoformat(),
            severity=rule.get("risk", "unknown"),
        )
        ET.SubElement(rr, _q("result")).text = _status_to_xccdf(rule.get("status"))
        ET.SubElement(rr, _q("title")).text = rule.get("title", "")
        ident = ET.SubElement(rr, _q("ident"), system="http://cce.mitre.org")
        ident.text = rule.get("cce") or rule["id"]

    return ET.ElementTree(root)


def main():
    if len(sys.argv) < 2:
        print("Usage: export_xccdf.py <result.json> [output.xml]", file=sys.stderr)
        sys.exit(1)
    infile = sys.argv[1]
    outfile = sys.argv[2] if len(sys.argv) > 2 else infile.replace(".json", ".xml")
    with open(infile, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    tree = to_xccdf(data)
    with open(outfile, "wb") as fh:
        tree.write(fh, encoding="utf-8", xml_declaration=True)
    print(f"XCCDF written to {outfile}: {len(data.get('results', []))} rule(s)")


if __name__ == "__main__":
    main()
